# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
commands:
  setup_aws_credentials_test: &setup_aws_credentials_test
    run:
      name: setup aws credentials test
      command: |
        ./set_up_aws_cred.sh
        echo "export AWS_PROFILE=grafo-naksha/test" | tee -a ~/.env
jobs:
  build-one:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.16.3

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    # working_directory: ~/repo

    steps:
      - checkout
      - run: npm install
      - run: npm test

  build-two:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.16.3

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    # working_directory: ~/repo

    steps:
      - run: echo "Just an echo"

workflows:
  version: 2.1
  build:
    jobs:
      - build-one

